
const $=id=>document.getElementById(id),v=id=>$(id)?.value||'';
function abnormal(id){return v(id)==='Present'}
function externalFindings(){const lines=[];if(abnormal('penisAbnormal')||abnormal('penisLesion')||abnormal('penisDischarge')||v('penisOther'))lines.push(`Penis/meatus: ${abnormal('penisAbnormal')?'abnormality present; ':''}${abnormal('penisLesion')?'lesion present; ':''}${abnormal('penisDischarge')?'discharge present; ':''}${v('penisOther')?v('penisOther'):''}`.replace(/; $/,''));if(abnormal('scrotumAbnormal')||abnormal('scrotumSwelling')||abnormal('scrotumMass')||abnormal('scrotumTender')||abnormal('scrotumLesion')||v('scrotumOther'))lines.push(`Scrotum: ${abnormal('scrotumSwelling')?'swelling; ':''}${abnormal('scrotumMass')?'mass; ':''}${abnormal('scrotumTender')?'tenderness; ':''}${abnormal('scrotumLesion')?'lesion; ':''}${v('scrotumOther')||''}`.replace(/; $/,''));[['Right','rightTestis'],['Left','leftTestis']].forEach(([side,k])=>{if(abnormal(k+'Abnormal')||abnormal(k+'Mass')||abnormal(k+'Tender')||v(k+'Size')||v(k+'Other'))lines.push(`${side} testis: ${abnormal(k+'Mass')?'mass; ':''}${abnormal(k+'Tender')?'tenderness; ':''}${v(k+'Size')?v(k+'Size')+'; ':''}${v(k+'Other')||''}`.replace(/; $/,''))});[['Right','rightEpid'],['Left','leftEpid']].forEach(([side,k])=>{if(abnormal(k+'Abnormal')||abnormal(k+'Swelling')||abnormal(k+'Mass')||abnormal(k+'Tender')||v(k+'Other'))lines.push(`${side} epididymis: ${abnormal(k+'Swelling')?'swelling; ':''}${abnormal(k+'Mass')?'mass; ':''}${abnormal(k+'Tender')?'tenderness; ':''}${v(k+'Other')||''}`.replace(/; $/,''))});[['Right','rightHernia'],['Left','leftHernia']].forEach(([side,k])=>{if(abnormal(k))lines.push(`${side} hernia: present${v(k+'Detail')?', '+v(k+'Detail'):''}.`)});return lines}
function prostateSummary(){if(v('dreStatus')!=='Examined')return '';const p=[];if(v('prostateSize'))p.push(v('prostateSize'));if(v('prostateSymmetry')==='Asymmetrical')p.push('asymmetrical');if(['Firm','Hard'].includes(v('prostateConsistency')))p.push(v('prostateConsistency').toLowerCase());if(v('prostateSurface')==='Irregular')p.push('irregular surface');if(v('prostateNodularity')==='Present')p.push('nodularity');if(v('prostateTenderness')==='Tender')p.push('tender');if(v('prostateOther'))p.push(v('prostateOther'));return p.length?'Prostate: '+p.join(', ')+'.':'No significant abnormal prostate finding recorded.'}
function urgentSummary(){const u=[];[['urgentRetention','acute urinary retention'],['urgentHaematuria','significant haematuria'],['urgentTestis','acute severe testicular pain/swelling'],['urgentTorsion','suspected torsion'],['urgentInfection','severe infection/systemic illness']].forEach(([id,label])=>{if(abnormal(id))u.push(label)});return u}
function buildClinicalSummary(){const lines=[];const e=externalFindings();if(e.length)lines.push('Significant abnormal findings:\n'+e.join('\n'));const p=prostateSummary();if(p)lines.push(p);const u=urgentSummary();if(u.length)lines.push('URGENT: '+u.join('; ')+' — immediate clinical attention.');return lines.length?lines.join('\n\n'):'No significant abnormal findings recorded.'}
function detailedNote(){const ext=externalFindings();const prostate=`Examination status: ${v('dreStatus')}${v('dreStatus')==='Examined'?`\nEstimated size: ${v('prostateSize')||'—'}\nSymmetry: ${v('prostateSymmetry')}\nConsistency: ${v('prostateConsistency')}\nSurface: ${v('prostateSurface')}\nNodularity: ${v('prostateNodularity')}\nTenderness: ${v('prostateTenderness')}\nOther findings: ${v('prostateOther')||'—'}`:''}`;const urg=urgentSummary();return `19.19 — MALE GENITOURINARY / PROSTATE EXAMINATION\n\nPatient: ${v('patientName')||'—'}   ID: ${v('patientId')||'—'}   Age: ${v('age')||'—'}\nExaminer: ${v('examiner')||'—'}\nIndication: ${v('indication')}\nConsent / privacy: ${v('consent')}\n\nEXTERNAL EXAMINATION\n${ext.length?ext.join('\n'):'No abnormal external finding recorded.'}\n\nPROSTATE — DIGITAL RECTAL EXAMINATION\n${prostate}\n\nURGENT FINDINGS\n${urg.length?urg.join('\n'):'None recorded.'}\n\nCLINICAL SUMMARY\n${buildClinicalSummary()}\n\nSAFETY NOTE\nAI must not equate prostate enlargement with cancer. Suspicious findings require clinician review and appropriate further evaluation.`}
function generateNote(){ $('clinicalNote').textContent=detailedNote();localStorage.setItem('jeevsetu_19_19',JSON.stringify(collect())); }
function collect(){const o={};document.querySelectorAll('input,select').forEach(e=>{if(e.id)o[e.id]=e.value});return o}
function clearAll(){if(!confirm('Clear all prostate examination entries?'))return;document.querySelectorAll('input').forEach(e=>e.value='');document.querySelectorAll('select').forEach(e=>e.selectedIndex=0);$('clinicalNote').textContent='Complete the examination and select “Generate Clinical Note”.';$('dreDetails').classList.add('hidden')}
$('dreStatus').addEventListener('change',()=> $('dreDetails').classList.toggle('hidden',v('dreStatus')!=='Examined'));
window.addEventListener('load',()=>{const raw=localStorage.getItem('jeevsetu_19_19');if(!raw)return;try{const o=JSON.parse(raw);Object.keys(o).forEach(k=>{const e=$(k);if(e)e.value=o[k]});$('dreDetails').classList.toggle('hidden',v('dreStatus')!=='Examined')}catch(e){}});
